# 粗略检查成员网站问题
name: Check members website
on:
  workflow_dispatch:
    inputs:
      note:
        description: "检查一次大概半小时，请等待"
        required: false
        type: boolean

jobs:
  checks:
    runs-on: ubuntu-latest
    timeout-minutes: 120
    permissions:
      issues: write
    steps:
      - name: Check members website
        uses: Jiaocz/travellings-link-checker@main
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          member-list: "https://raw.githubusercontent.com/travellings-link/travellings/master/member.md"
