# Issue 创建/reopen 时自动放置到工作台 “待审核” 列，并标记“待处理”标签

name: Label and move to project on issue open
on:
  issues:
    types: [opened, reopened]

jobs:
  move-to-project:
    runs-on: ubuntu-latest
    steps:
      - uses: alex-page/github-project-automation-plus@5bcba1c1c091a222584d10913e5c060d32c44044
        with:
          project: "工作台"
          column: "待审核"
          repo-token: ${{ secrets.GITHUB_TOKEN }}

  label-issue:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Label issue
        uses: andymckay/labeler@e6c4322d0397f3240f0e7e30a33b5c5df2d39e90
        with:
          add-labels: "待处理"
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          ignore-if-labeled: true
